stages:
  - build

build-job:
  stage: build
  image: node:18
  script:
    - echo "cd into the frontend directory"
    - cd frontend
    - echo "install the node_modules"
    - npm install
    - echo "build the app"
    - npm run-script build
    - echo "build was successful!"
