stages:
  - build
  - test

build-job:
  stage: build
  image: node:18
  script:
    - echo "cd into the frontend directory"
    - cd frontend
    - echo "install the node_modules"
    - npm install
    - echo "build the app"
    - npm run-script build
    - echo "build was successful!"

jest_tests:
  stage: test
  image: node:18
  script:
    - cd frontend
    - npm install
    - npm test

selenium_tests:
  stage: test
  image: python:3.9-slim
  services:
    - selenium/standalone-chrome
  before_script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r frontend/selenium/requirements.txt
  script:
    - cd frontend/selenium
    - python3 -m pytest

backend_tests:
  stage: test
  image: python:3.6-stretch
  before_script:
    - pip install -r backend/requirements.txt
    - pip install google-search-results
    - pip install black
  script:
    - cd backend
    - python3 tests.py
    - black *.py
    - cd database
    - black *.py

postman_test:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - cd backend
    - newman run Postman.json