stages:
  - build
  - test

build-job:
  stage: build
  image: node:18
  script:
    - echo "cd into the frontend directory"
    - cd frontend
    - echo "install the node_modules"
    - npm install
    - echo "build the app"
    - npm run-script build
    - echo "build was successful!"

jest_tests:
  stage: test
  image: node:18
  script:
    - cd frontend
    - npm install
    - npm test

# selenium_tests:
#   stage: test
#   image: python:3.8
#   services:
#     - selenium/standalone-chrome
#   script:
#     - python3 -m pip install selenium
#     - python3 -m pip install unittest2
#     - python3 -m pip install webdriver_manager
#     - python3 -m pip install packaging
#     - python3 frontend/guitests.py

backend_tests:
  stage: test
  image: python:3.6-stretch
  before_script:
    - pip install -r backend/requirements.txt
    - pip install google-search-results
    - pip install black
  script:
    - cd backend
    - python3 tests.py
    - black *.py
    - cd database
    - black *.py

postman_test:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - cd backend
    - newman run Postman.json